#!/usr/bin/env bash
export JAVA_HOME="${JAVA_HOME:-/usr/local/opt/openjdk/libexec/openjdk.jdk/Contents/Home}"
exec "${JAVA_HOME}/bin/java" \
  ${comment# --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED }\
  ${comment# --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED }\
  ${comment# --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED }\
  ${comment# --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED }\
  ${comment# --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED }\
  -jar "$HOME/.config/nvim/script/google-java-format.jar" "$@"
